module.exports = { 
    MAX_LEVEL_FIGHTER_5  : 20,
    MAX_LEVEL_FIGHTER_6  : 40,
    MAX_LEVEL_FIGHTER_7  : 55,
    MAX_LEVEL_FIGHTER_8  : 70,
    MAX_LEVEL_FIGHTER_9  : 85, 
    MAX_LEVEL_FIGHTER_10 : 100,

    VIOLET_FRAQMENT_COUT : 3,
    BLUE_FRAQMENT_COUT : 4,
    GREEN_FRAQMENT_COUT : 5,
    DIAMANTS_FRAQMENT_COUT : 70,
    TICKETS_FRAQMENT_COUT : 6
}